### ISSUE TITLE
Add rem_vertex! to AbstractGraph interface?

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaGraphs/LightGraphs.jl#1467]
Would it be possible or make sense to add `rem_vertex!` to the `AbstractGraph` interface? The docstring for `SimpleGraphs.rem_vertex!` in v1.3 says this:

> This operation has to be performed carefully if one keeps external data structures indexed by edges or vertices in the graph, since internally the removal is performed swapping the vertices v and |V|, and removing the last vertex |V| from the graph. After removal the vertices in g will be indexed by 1:|V|−1.

However, that appears to be an implementation detail specific to `AbstractSimpleGraph`. Suppose I want to create a new type called `GraphWrapper` that wraps any `AbstractGraph` type. And suppose that `GraphWrapper` contains fields which are indexed by the vertex indices. If I want to add `rem_vertex!(gw::GraphWrapper, v)`, there doesn't seem to be a way to do it that would work for any `AbstractGraph`, since the `AbstractGraph` interface does not specify the behavior of `rem_vertex!`. For now it seems like I can only make a wrapper that wraps a `SimpleGraph`, since the `rem_vertex!` behavior is only specified for an `AbstractSimpleGraph`.

**Comment by CameronBieganek** [comment]
Oops, I think it added the bug label automatically.

**Comment by CameronBieganek** [comment]
I could be wrong here, but at first glance it seems like this might require some rather large changes to the API. I'm thinking that this might require introducing a notion of `AbstractVertex`, with an interface something like the following:

```julia
v1 = add_vertex!(g)   # typeof(v1) <: AbstractVertex
v2 = add_vertex!(g)   # typeof(v2) <: AbstractVertex
add_edge!(g, v1, v2)
rem_vertex!(g, v2)
```

Sorry if this is way off base. I haven't been following the v2.0 development. At any rate, I suspect that this would require too large of a change to be considered at the moment.

**Comment by sbromberger** [comment]
It's not a good idea. StaticGraphs.jl doesn't allow graph modifications after construction, for example. There are a lot of use cases where adding/removing vertices and edges are not allowed.

We were toying with an "IsMutable" trait but it never really got traction.

**Comment by CameronBieganek** [comment]
Well, I was thinking that `rem_vertex!` would be an optional part of the interface. Mutable graph types need to implement `add_vertex!` and `rem_vertex!`, but immutable graph types do not. Of course if I wrap a `StaticGraph`, then I won't be able to add or remove edges. But if I wrap any graph that can be mutated, there isn't a generic way to add or remove edges in the graph wrapper.

For now I'm going to take the easy way out and restrict my graph wrapper to only using subtypes of `AbstractSimpleGraph`. :)

**Comment by CameronBieganek** [comment]
Is there somewhere on github where the traits discussion is occuring? It does seem like it would be useful to formalize the mutability interface. Not just for my hypothetical `GraphWrapper`, but for any new graph type that is mutable. Currently the `add_*` and `rem_*` methods are not part of the `AbstractGraph` interface, so it's not clear how to implement those methods in a way that is compatible with the rest of the LightGraphs.jl functionality.

**Comment by sbromberger** [comment]
There is no such thing as "an optional part" of an interface, when you get down to it. The interface is the contract - that is, it specifies exactly what you need to implement in order to take full advantage of the higher-level functionality. 

The problem we'd run into with this plan is as follows: we add an API for `rem_vertex!`. Then people see that as part of the API and start building functions that use it (perhaps it's necessary; perhaps it's just the easier of several ways of doing something). But all of a sudden, a graph type that implements `AbstractGraph` now can't use a subset of functionality that is designed to work with `AbstractGraph`. This is not an ideal scenario (it's actually one of the things we fixed during the 0.x -> 1.0 transition).

As far as traits discussion goes, there is no current discussion as far as I'm aware. Feel free to start one and contribute code. I think that's what @matbesancon did with his latest trait.

**Comment by sbromberger** [comment]
I knew this sounded familiar.

ref: https://github.com/JuliaGraphs/LightGraphs.jl/pull/1222
ref: https://github.com/JuliaGraphs/LightGraphs.jl/pull/1275

**Comment by CameronBieganek** [comment]
Well, I'm no expert on interfaces, but according the [Base docs](https://docs.julialang.org/en/v1/manual/interfaces/) on interfaces, there are a number of "Optional methods" for the iteration, abstract array, and broadcasting interfaces. So yes, I think you can have in interface with optional methods. Julia interfaces are informal anyway. If I try to use a hypothetical mutability interface on a `StaticGraph` then I probably just get a method error.

**Comment by CameronBieganek** [comment]
The mutable trait PR is interesting, but it doesn't solve my problem of keeping external data synced with a wrapped `AbstractGraph` when vertices are deleted from the wrapped graph, because it's still only possible to refer to vertices by their integer code. In other words, to do this generically I think I would need some way to refer to an instance of an `AbstractVertex`...

**Comment by sbromberger** [comment]
>  So yes, I think you can have in interface with optional methods

I'm don't mean to imply that there's a technical reason it can't be done; what I'm trying to say is that we've been down this road before in pre-1.0 days and learned that this is not a great way to do things, especially on an interface that's already got widespread adoption (e.g., `AbstractGraph`). If you wanted to create a trait, that might be something to consider, but the problem is that if an API defines a core function, then people are going to build things using it, and if it breaks for some subset of types that implement everything else BUT that function, then there's no easy way to tell up front what functions within the LightGraphs ecosystem will work with what graph types.

**Comment by sbromberger** [comment]
> but it doesn't solve my problem of keeping external data synced with a wrapped `AbstractGraph` when vertices are deleted from the wrapped graph

This sort of suggests that you want your own graph type here.

**Comment by CameronBieganek** [comment]
> This sort of suggests that you want your own graph type here, though

Well, the truth is I'm creating my own meta-graph type. So I want to be able to wrap *any* `AbstractGraph` with my meta-graph type. But unfortunately I can't implement `rem_vertex!(mg::MyMetaGraph, v)` in a generic way that will work for *any* `AbstractGraph`, since `rem_vertex!` is not part of the interface.

> AbstractVertex = Integer is the only portable/generic option.

But this is *not* a generic option, because if you want to create a mutable graph type that wraps an `AbstractGraph`, you have to rely on the implementation details of `SimpleGraphs.rem_vertex!`:

> This operation has to be performed carefully if one keeps external data structures indexed by edges or vertices in the graph, since internally the removal is performed swapping the vertices v and |V|, and removing the last vertex |V| from the graph. After removal the vertices in g will be indexed by 1:|V|−1.

Of course other mutable graph types might do something completely different, so the wrapped graph type will only work if you wrap an `AbstractSimpleGraph`.

We had a very similar conversation a while ago in https://github.com/JuliaGraphs/MetaGraphs.jl/pull/97#issuecomment-623214676. In that comment, as in this thread, I pointed out that the lack of a generic vertex concept makes it very difficult to extend LightGraphs in certain directions.

I don't want to beat a dead horse here. I know this would be a huge change to the overall API. But it's something that is worth thinking about in order to make LightGraphs more extensible.

**Comment by sbromberger** [comment]
> So I want to be able to wrap any `AbstractGraph` with my meta-graph type.

I wouldn't do this. I'd pick a concrete implementation `<: AbstractGraph` and use that. Each concrete implementation of `AbstractGraph` makes different design/performance tradeoffs that simply might not work in your environment.

> But this is not a generic option, because if you want to create a mutable graph type that wraps an AbstractGraph, you have to rely on the implementation details of `SimpleGraphs.rem_vertex!`

Yes. This is deliberate, because `rem_vertex!` is not implemented for `AbstractGraph`, and *can't* be as discussed above. What happens if we make `rem_vertex!` part of the `AbstractGraph` API, and I decide to use a `StaticGraph` inside your wrapper?

> Of course other mutable graph types might do something completely different, so the wrapped graph type will only work if you wrap an `AbstractSimpleGraph`.

Ah, but *here* is a solution, then. Wrap `AbstractSimpleGraph`. `rem_vertex!` is part of its API.

**Comment by CameronBieganek** [comment]
> I'd pick a concrete implementation `<: AbstractGraph` and use that.

To clarify, I'm not writing an application specific meta-graph. I'm writing a generic meta-graph library. In other words, I'm writing my own replacement for MetaGraphs.jl. So it would be ideal if my new meta-graph type can wrap any `AbstractGraph` type. That way the user of my library can decide which particular `AbstractGraph` implementation is best for their project. My new meta-graph library can be found here: https://github.com/CameronBieganek/PropertyGraphs.jl However, the code is very preliminary, so don't read too much into it.

To put it another way, this issue might not affect the average *user* of LightGraphs, but it affects *library developers* who want to implement a generic graph extension that extends LightGraphs by wrapping an `AbstractGraph`. For the particular case of my PropertyGraphs.jl package, I want to be able wrap any `AbstractGraph` implementation. It would defeat the purpose of creating the library if I had to pick just one particular graph implementation to wrap.

> What happens if we make `rem_vertex!` part of the `AbstractGraph` API, and I decide to use a `StaticGraph` inside your wrapper?

Normally in Julia if you attempt to use an object with an interface that has not been implemented for that object, you get a runtime exception. Example:

```julia
julia> struct A
           x
       end

julia> for v in A([1, 2, 3])
           println(v)
       end
ERROR: MethodError: no method matching iterate(::A)
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:603
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:603
  iterate(::ExponentialBackOff) at error.jl:253
  ...
Stacktrace:
 [1] top-level scope at ./REPL[2]:1
```

I would expect exactly the same thing to happen if a user uses a `PropertyGraph` (my meta-graph type) to wrap a `StaticGraph`. When they call `rem_vertex!` on the meta-graph wrapper, they will get a runtime exception. That's perfectly normal and to be expected. I don't see why we need to be so scared about that possibility. Julia is a dynamic language, so some responsibility for writing correct code has to fall on the user.

**Comment by CameronBieganek** [comment]
I just noticed that there are a number of functions in the `src/operators.jl` file (on the master branch) that use `add_edge!`, `add_vertex!`, `rem_edge!`, or `rem_vertex!`. These functions claim to work on any `AbstractGraph`, but that's not possible since the `AbstractGraph` interface does not include the `add_*` and `rem_*` functions. So any LightGraphs function which uses an `add_*` or `rem_*` function internally ***does not*** conform to the nominal interface for `AbstractGraph`.

Consider this sentence from the manual:

> As long as your graph structure is a subtype of `AbstractGraph` and implements the following API functions with the given return values, all functions within the LightGraphs package should just work:

That sentence is incorrect, since many LightGraphs functions (e.g. `complement`, `reverse`, `intersect`, `difference`, `join`, `union`, `induced_subgraph`, etc.) internally use `add_*` or `rem_*`, and therefore those functions cannot be expected to work on any graph that implements the `AbstractGraph` interface as it is currently defined.

**Comment by sbromberger** [comment]
You're right,  but it's bad practice and definitely an example of legacy inconsistency. It's something that's been fixed in my private branch. I have not decided whether and how to release the new/correct code.

**Comment by sbromberger** [comment]
I'm doing some housekeeping on issues this week and would like to close this out since I think the discussion has run its course. If you'd like to continue, please feel free to use the closed issue or create a new one. Thanks.
